---
- name: "Find distro"
  debug:
    msg: "{{ ansible_distribution }}"

- name: "Operating system not supported"
  fail:
    msg: "FATAL: {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported. Please check supported versions"

- name: "Check for Internet connectivity and name resolution"
  ansible.netcommon.net_ping:
    dest: "google.pt"

- name: "Update package manager"
  apt:
    update_cache: yes
  become: yes
  become_user: "{{ local_become_user }}"

- name: "Upgrade the system"
  apt:
    upgrade: dist
  become: yes
  become_user: "{{ local_become_user }}"
